[package]
name = "defaria"
version = "0.1.0"
edition = "2021"

[features]
default = ["dev"]
dev = ["bevy/dynamic_linking"]

[dependencies]
bevy = "0.15.1"
bevy_flycam = "0.15.0"
noise = "0.9.0"

[profile.dev]
opt-level = 1
